---
nixpkgs_config_dir: "{{ ansible_env.HOME }}/.config/nixpkgs"

nixpkgs_config:
  allowUnfree: "true"

nixpkgs_default_profiles:
  - "alegreya"
  - "delta"
  - "devenv"
  - "fluxcd"
  - "gitu"
  - "gitui"
  - "go"
  - "julia-mono"
  - "k9s"
  - "kubectl"
  - "nushell"
  - "overpass"
  - "protonvpn-gui"
  - "rustup"
  - "slack --impure"
  - "starship"
  - "tealdeer"
  - "terraform --impure"
  - "yazi"
  - "zellij"
  - "zoxide"

nixpkgs_profiles: []
nixpkgs_group_profiles: []
nixpkgs_host_profiles: []

nixpkgs_all_profiles: >-
  {{ nixpkgs_default_profiles
  + nixpkgs_profiles
  + nixpkgs_group_profiles
  + nixpkgs_host_profiles }}
