---
nixpkgs_config_dir: "{{ ansible_env.HOME }}/.config/nixpkgs"

nixpkgs_config:
  allowUnfree: "true"

nixpkgs_default_profiles:
  - "ansible-language-server"
  - "bash-env-json"
  - "bat"
  - "bat-extras.batdiff"
  - "bat-extras.batgrep"
  - "bat-extras.batman"
  - "bat-extras.batpipe"
  - "bat-extras.batwatch"
  - "delta"
  - "devenv"
  - "carapace"
  - "fluxcd"
  - "gitu"
  - "gitui"
  - "go"
  - "isort"
  - "k9s"
  - "kubectl"
  - "lsp-ai"
  - "moar"
  - "nixfmt-rfc-style"
  - "nushell"
  - "nushellPlugins.skim"
  - "nushellPlugins.query"
  - "python312Packages.python-lsp-server"
  - "python312Packages.python-lsp-ruff"
  - "python312Packages.pylsp-mypy"
  - "python312Packages.pylsp-rope"
  - "rustup"
  - "starship"
  - "tealdeer"
  - "terraform --impure"
  - "uv"
  - "vagrant --impure"
  - "yazi"
  - "zellij"
  - "zk"
  - "zoxide"

nixpkgs_profiles: []
nixpkgs_group_profiles: []
nixpkgs_host_profiles: []

nixpkgs_all_profiles: >-
  {{ nixpkgs_default_profiles
  + nixpkgs_profiles
  + nixpkgs_group_profiles
  + nixpkgs_host_profiles }}
