[identities]
rking = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ7Baqq253Sck6C1tzEjdfw8OGjQRNap8FtPmU6FNB4f ryantking@protonmail.com"

[groups]
all = [ "rking" ]
machines = [ ]

[[paths]]
glob = "home/profiles/git/*.age"
groups = [ "all" ]

[[paths]]
glob = "etc/doom/lisp/*.age"
groups = [ "all" ]
