[global]
excludes = [ "etc/emacs/**" ]

[formatter.nix]
command = "nixpkgs-fmt"
includes = [ "*.nix" ]

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = [ "*.go" ]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
    "*.css",
    "*.html",
    "*.js",
    "*.json",
    "*.jsx",
    "*.md",
    "*.mdx",
    "*.scss",
    "*.ts",
    "*.yaml",
]
excludes = ["CHANGELOG.md"]

[formatter.shell]
command = "/bin/sh"
options = [
    "-euc",
    """
# First lint all the scripts
# shellcheck "$@"
# Then format them
shfmt -i 2 -s -w "$@"
    """,
    "--",
]
includes = ["*.sh"]
