[global]
excludes = [
  "usr/**",
  "src/site/themes/archie/**",
  "src/site/themes/hugo-book/**"
]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.go]
command = "goimports"
options = ["-w"]
includes = ["*.go"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.toml",
  "*.ts",
  "*.yaml"
]
excludes = ["CHANGELOG.md"]

[formatter.shell]
command = "prettier"
options = ["--write", "--parser", "sh"]
includes = ["Dckerfile", ".gitignore", ".envrc", "*.sh"]
