---
- name: "Manage Tailscale VPN"
  hosts: all
  become: true
  gather_facts: false

  # NOTE: This doesn't work yet since tailscale up breaks SSH

  roles:
    - role: tailscale
      tags: ["tailscale"]
