---
git_packages: ["git", "git-crypt"]

git_workspace_dir: "{{ ansible_env.HOME }}/Workspaces"

git_default_workspaces:
  - name: private
    transfer: true

git_workspaces: []
git_group_workspaces: []

git_all_workspaces: >-
  {{ git_default_workspaces
  + git_workspaces
  + git_group_workspaces }}
