---
apt_default_packages:
  - 7zip
  - build-essential
  - curl
  - dnsutils
  - ffmpeg
  - git
  - git-crypt
  - imagemagick
  - jq
  - net-tools
  - nmap
  - postgresql-client
  - tailscale
  - tuned
  - unzip
  - vim
  - wget

apt_packages: []
apt_group_packages: []
apt_host_packages: []

apt_all_packages: >-
  {{ apt_default_packages
  + apt_packages
  + apt_group_packages
  + apt_host_packages }}

apt_default_repos:
  - name: tailscale
    key_url: >-
      https://pkgs.tailscale.com/stable/ubuntu/{{
      ansible_distribution_release }}.noarmor.gpg
    source: >-
      deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg]
      https://pkgs.tailscale.com/stable/ubuntu
      {{ ansible_distribution_release }} main

apt_group_repos: []
apt_host_repos: []

apt_all_repos: >-
  {{ apt_default_repos
  + apt_group_repos
  + apt_host_repos }}
