---
apt_default_packages:
  - 7zip
  - build-essential
  - curl
  - dnsutils
  - fish
  - fonts-ibm-plex
  - fonts-symbola
  - git
  - git-crypt
  - jq
  - net-tools
  - nmap
  - postgresql-client
  - tuned
  - unzip
  - vim
  - wget

apt_packages: []
apt_all_packages: "{{ apt_default_packages + apt_packages }}"

apt_default_ppas: ["fish-shell/beta-4"]

apt_ppas: []
apt_all_ppas: "{{ apt_default_ppas + apt_ppas }}"
