---
apt_default_packages:
  - build-essential
  - certbot
  - curl
  - direnv
  - dnsutils
  - fd-find
  - git-crypt
  - net-tools
  - nmap
  - npm
  - postgresql-client
  - ripgrep
  - tealdeer
  - ttfautohint
  - unzip
  - vim
  - wget

apt_group_packages: []
apt_host_packages: []

apt_all_packages: >-
  {{ apt_default_packages
  + apt_group_packages
  + apt_host_packages }}

apt_group_debs: []
apt_host_debs: []

apt_all_debs: >-
  {{ apt_group_debs
  + apt_host_debs }}
