---
apt_default_packages:
  - 7zip
  - build-essential
  - curl
  - dnsutils
  - ffmpeg
  - fish
  - fonts-ibm-plex
  - fonts-symbola
  - git
  - git-crypt
  - imagemagick
  - jq
  - net-tools
  - nmap
  - postgresql-client
  - tailscale
  - tuned
  - unzip
  - vim
  - wget

apt_packages: []
apt_all_packages: "{{ apt_default_packages + apt_packages }}"

apt_default_repos:
  - name: fish-shell
    source: ppa:fish-shell/beta-4

  - name: tailscale
    source: >-
      deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg]
      https://pkgs.tailscale.com/stable/ubuntu
      {{ ansible_distribution_release }} main
    key_url: >-
      https://pkgs.tailscale.com/stable/ubuntu/{{
      ansible_distribution_release }}.noarmor.gpg

apt_repos: []
apt_all_repos: "{{ apt_default_repos + apt_repos }}"
