---
apt_default_packages:
  - 7zip
  - build-essential
  - curl
  - dnsutils
  - fish
  - fonts-ibm-plex
  - fonts-symbola
  - git
  - git-crypt
  - glow
  - gh
  - gum
  - jq
  - net-tools
  - nmap
  - postgresql-client
  - python3-click
  - python3-sh
  - tig
  - tuned
  - unzip
  - vim
  - wget
  - yq

apt_packages: []
apt_all_packages: "{{ apt_default_packages + apt_packages }}"

apt_repositories: []

apt_default_ppas: ["fish-shell/beta-4"]

apt_ppas: []
apt_all_ppas: "{{ apt_default_ppas + apt_ppas }}"
