[yabai]
src.git = "https://github.com/koekeishiya/yabai"
fetch.git = "https://github.com/koekeishiya/yabai"

[chemacs]
src.git = "https://github.com/plexus/chemacs2.git"
fetch.git = "https://github.com/plexus/chemacs2.git"

[fennel]
src.git = "https://github.com/bakpakin/Fennel.git"
fetch.git = "https://github.com/bakpakin/Fennel.git"

[goimapnotify]
src.git = "https://gitlab.com/shackra/goimapnotify.git"
fetch.git = "https://gitlab.com/shackra/goimapnotify.git"

[nord-dircolors]
src.git = "https://github.com/arcticicestudio/nord-dircolors.git"
fetch.git = "https://github.com/arcticicestudio/nord-dircolors.git"

[stackline]
src.git = "https://github.com/AdamWagner/stackline.git"
fetch.git = "https://github.com/AdamWagner/stackline.git"
