[trashstation]
address = "192.168.1.75"
tailscale = "100.112.62.110"

[trashstation.keys]
pgp = "TODO"
age = "age15khpycddvy4n8qg3ynx8zssx7sq5e7fdhkw0pxvh47tzjk5sp5ts9pg8nw"
ssh = [
     "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPHhyWY6inRdbr+og3gYMM/tRQeVsDsdgaghWcZRQhLa rking@trashstation",
     "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDshTJoa3tXD5+gEkkg+//60Y7hAS0FJfbQcco3KIRVCZbR8T1YLCHwpL1npTBIrgm+IG4I5isI3oAjkTYNaHpNK3pU67GSbbjVODTC2vBa3Mbxc2izkQaegckp09Eg6x6i5mSswVMRGMYTe0xlewdNI7E7SMYJKup67baHC1qCq0CCzTY0C0YZCEp3WkjGiXXgXnVEeTTcidBx+jsBSa2FcFB5AnNh0ile+pXppKMwGfIk5STTUMWNnb/ilhvotNoOJrkECDPCZikyh40q04MK9rEnXmBjis+kZP3kNJK+DBgeTyYcnR+paALRn+CrtBC281Z8HBdGBo3aDkjuOUviYGhEfFNLCRqT6VSDuchm8ONqiB/WeiQMPj4kQ6r9tltxRdsfxSgvbvKb6cE5T4il5p0kyX65MKGNpnD5gtbH2fsI3nN/RRqWccEvqybYezuV+88Hs75kWTgF0vkqonu+VRjzILz+OJpaiu9RGXkNyXs/gyQQSP6PWpowpSHpYVd9CDTmxdj5co7ymhDGAr0SVSUAvNmMzGazzUtXh4YuivPoYGiA1rPVRXE5EqjHCwWCGToHypuzZj48ep95+HG5m2zqxT5/WGPAWMlHnq0rK5wEpYA7GXwmOQIV5EMJ234CAzReL7nnE9cOGGQCMU4zYOLm5C7XVlcH11cvO0vJOw== rking@trashstation"
]

[shoyobook]
address = "192.168.1.43"
tailscale = "100.83.79.25"

[shoyobook.keys]
pgp = "0xB6A2C0B84A008984"
age = "age1lvt9ktph2n8qj3p8vp6ruh5v87udzdf56wt7rzm869ad0h438fdqpdadd5"
ssh = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGqZquzHm0ucwIyLkjIl0OSzgvd6Nn1IKaoZHCS8Rwrr rking@shoyobook",
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVh0HzdI4/OgO0/aJcIv9cN+Fcu+mxGsXq8fN0Es6ArTnCcB54L3wNwNUFl+TrM+Jx5p63UI3TMNLwF+oyJRhd1OBRfe7tYLt/xUYMJ5MTKB4ldpVo9FnVvEdltZojzOLVXnWBFSBXENaEZBv/wuTrYVQOoZbeTBHajUTREQpnp/xjuwxVmtf22I4iaMeXtBPww4xzrgmuubCRqv/qb89/L3HffYUfDe0InbS3o31/G5FxQckVwovMxaOc+U3G1WJpV/GIAZuoALpFGHYO9LRlX1WhlH3CgXnnL7GJ8Gdzt0WoI0unL7MsE4DMYy/6A+SCt0EY4lMBfmYJZ0OpNqkS4HGtOTzxSs8NCEujdxgYHAbOOrhd+SjVwnGa8tT92NpfRo+eE8MWjJJFkCynsRLFqn+LDKrboKiTE6d3C0olTRZGf1oVJ+1nKrECzodg6m60rL1YvkETfeRsxEN54ypeQu+JhwkhUVCJuX3As5jY9ilwXrnLwQLPE7vuJj7Y60TfpUzRncYHqmQ+y9yuRLV5pMV1mNE3cD9EeIpZ2alL6Km9Oz6OukoJHUWQjnGxpLb7x+ONZkKjNoqyOQ6LAe6nVl5SLbumse7uMBHI1HSgsm7cCuY7LZ6jK7LvGhRarU2qYmQ9B/xU6//YHhbqW86Ypts3bTeN6wi/qmZDOVTURQ== rking@shoyobook"
]

[triangle-vm]
address = "172.16.41.128"
tailscale = ""

[triangle-vm.keys]
pgp = "4B66E65AB7617B56E5E5CC41CD59104FF43D2AB2"
age = ""
ssh = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBl8CmPSzmzRi2FxB4mELiG4WOHmFP381LdJjKjqNWh9 ryan@triangle-vm",
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAHrUP4bOycjZXZ6/i+YmXpISlNsj48dnQ1wQSvT6+YtQmGvO/gjBT0hTA8LGZSCX8i6wDYX/50/hTlqVvmSaM2ekX15xk0bSWT5Xemio5EZINVHjdNoAIWXj1+e/CnZ67k3sz9LDoXmcbcBTCz33HP3Wpj9VSqCNdTwIT8YqiWbSV/MFYjfELECwBLlFlc+Toj4snzh4ZObeZHLA3fOUYbxHOLoWkqxq8FvDQ63yo0Jqo6OR9dlHQAAw+5D8yse50hEx5jsfGVtaQjOg5YQlH0bGr/2QoYKwNHQFwPANvHmDbuqLgBImtbm2/bqV+LCPN82tK88j0irQ+4KC9PEcL/t6aqbJUU6Nvdg48O60QyXOsdzdLeZOMa0TiWEycV6BWzELJGpPzOp+MFzxYcSkReK0bAxD+2ggRsx50JY/I3h9w7lbjCBWK7GRaD2BfE8BbdzMm4u95M5C4OMnFC9lW2scFRjih479V3MeGnF/CcGAxNC8XwKvP06E1twarmbUyPeu8zhwduP0P5qEgFBo1nV4wrri88Zdse8y9ha1F/adnOAjOgLSPv9ZRomyP4QX1PbB0qRp/9XUwSG81e/2BlyAW55/6PJLJ+2dwbWV0fQyOieE/b5A1ygxOTUWn5DhDQbXy4Jf+PvlZVPxwigT+YiHLx0bMA3NqooDMgahuvQ== ryan@triangle-vm"
]