---
apt_repositories:
  - name: wezterm
    key_url: https://apt.fury.io/wez/gpg.key
    key_file: wezterm-fury.gpg
    key_dearmor: true
    uris: ["https://apt.fury.io/wez/"]
    suites: ["*"]
    components: ["*"]

  - name: brave-browser
    key_url: >-
      https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    key_file: brave-browser-archive-keyring.gpg
    uris: ["https://brave-browser-apt-release.s3.brave.com/"]
    suites: ["stable"]
    components: ["main"]

  - name: paul4us
    key_file: paul4us.gpg
    uris:
      - "http://download.opensuse.org/repositories/home:/paul4us/xUbuntu_24.10/"
    trusted: true
    suites: ["/"]

apt_packages:
  - alacritty
  - brave-browser
  - evolution
  - ffmpeg
  - gir1.2-ayatanaappindicator3-0.1
  - gnome-shell-extension-appindicator
  - imagemagick
  - klassy
  - libayatana-appindicator3-1
  - rhythmbox
  - wezterm

apt_ppas:
  - name: aslatter/ppa
    release: noble

nix_packages:
  - "alegreya"
  - "julia-mono"
  - "overpass"
  - "protonvpn-gui"
  - "slack --impure"

snap_packages:
  - name: alacritty
    classic: true
  - name: discord
  - name: obsidian
    classic: true
  - name: signal-desktop
  - name: telegram-desktop
  - name: vlc
