---
browser: "brave"

apt_packages:
  - evolution
  - gir1.2-ayatanaappindicator3-0.1
  - gnome-shell-extension-appindicator
  - libayatana-appindicator3-1
  - rhythmbox

nix_packages:
  - "alegreya"
  - "julia-mono"
  - "overpass"
  - "protonvpn-gui"
  - "slack --impure"

snap_packages:
  - name: alacritty
    classic: true
  - name: "{{ browser }}"
  - name: discord
  - name: obsidian
    classic: true
  - name: signal-desktop
  - name: telegram-desktop
  - name: vlc
