---
browser: "brave"

apt_packages:
  - alacritty
  - evolution
  - ffmpeg
  - gir1.2-ayatanaappindicator3-0.1
  - gnome-shell-extension-appindicator
  - imagemagick
  - libayatana-appindicator3-1
  - rhythmbox

apt_ppas:
  - name: aslatter/ppa
    release: noble

nix_packages:
  - "alegreya"
  - "julia-mono"
  - "overpass"
  - "protonvpn-gui"
  - "slack --impure"

snap_packages:
  - name: alacritty
    classic: true
  - name: "{{ browser }}"
  - name: discord
  - name: obsidian
    classic: true
  - name: signal-desktop
  - name: telegram-desktop
  - name: vlc
