tick_rate = 50

[ui]
use_nerd_font_icons = false
ui_scale = 80
show_help_bar = false
show_preview_panel = true
input_bar_position = "top"
theme = "default"

[previewers.file]
theme = "ansi"

[keybindings]
quit = ["esc", "ctrl-c"]
select_next_entry = ["down", "ctrl-n"]
select_prev_entry = ["up", "ctrl-p"]
select_next_page = "pagedown"
select_prev_page = "pageup"
scroll_preview_half_page_down = "ctrl-d"
scroll_preview_half_page_up = "ctrl-u"
toggle_selection_down = "tab"
toggle_selection_up = "backtab"
confirm_selection = "enter"
copy_entry_to_clipboard = "ctrl-y"
toggle_remote_control = "ctrl-r"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-h"
toggle_preview = "ctrl-o"

# [keybindings.RemoteControl]
# quit = "esc"
# select_next_entry = ["down", "ctrl-n", "ctrl-j"]
# select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
# select_next_page = "pagedown"
# select_prev_page = "pageup"
# select_entry = "enter"
# toggle_remote_control = "ctrl-r"
# toggle_help = "ctrl-g"
# toggle_preview = "ctrl-o"

# [keybindings.SendToChannel]
# quit = "esc"
# select_next_entry = ["down", "ctrl-n", "ctrl-j"]
# select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
# select_next_page = "pagedown"
# select_prev_page = "pageup"
# select_entry = "enter"
# toggle_send_to_channel = "ctrl-s"
# toggle_help = "ctrl-g"
# toggle_preview = "ctrl-o"

[shell_integration.channel_triggers]
"alias" = ["alias", "unalias"]
"env" = ["export", "unset"]
"dirs" = ["cd", "ls", "rmdir"]
"files" = [
  "cat",
  "less",
  "head",
  "tail",
  "vim",
  "nano",
  "bat",
  "cp",
  "mv",
  "rm",
  "touch",
  "chmod",
  "chown",
  "ln",
  "tar",
  "zip",
  "unzip",
  "gzip",
  "gunzip",
  "yazi",
  "xz",
]
"git-diff" = ["git add", "git restore"]
"git-branch" = [
  "git checkout",
  "git branch",
  "git merge",
  "git rebase",
  "git pull",
  "git push",
]
"docker-images" = ["docker run"]
"git-repos" = ["nvim", "code", "hx", "git clone"]

[shell_integration.keybindings]
"smart_autocomplete" = "ctrl-f"
"command_history" = "ctrl-r"
