---
- name: "Manage AppImageLauncher"
  hosts: "desktop:&ubuntu"
  become: true
  gather_facts: false
  tags: ["play::appimagelauncher", "skip::appimagelauncher"]

  vars:
    appimagelauncher_releases: >-
      https://github.com/TheAssassin/AppImageLauncher/releases/download
    appimagelauncher_version: "3.0.0-alpha-4"
    appimagelauncher_build: "gha253.36951ec"
    appimagelauncher_deb: >-
      appimagelauncher_{{ appimagelauncher_version
      }}-{{ appimagelauncher_build }}_amd64.deb

  tasks:
    - name: "Download .deb packages"
      ansible.builtin.get_url:
        url: >-
          {{ appimagelauncher_releases }}/v{{ appimagelauncher_version
          }}/{{ appimagelauncher_deb }}
        dest: "/tmp/{{ appimagelauncher_deb }}"
        mode: "0644"

    - name: "Install downloaded .deb packages"
      ansible.builtin.apt:
        deb: "/tmp/{{ appimagelauncher_deb }}"
        state: present
