---
- name: "Manage the Nix package manage"
  hosts: all

  roles:
    - role: fontconfig
      fontconfig_dependent_configs:
        - "{{ nix_fontconfig_dependent_configs }}"
      when: inventory_hostname in groups['ubuntu']
      tags: ["role::fontconfig", "skip::fontconfig"]

    - role: nix
      tags: ["role::nix", "skip::nix"]
