---
- name: "Install the latest Zoom version from the .deb"
  hosts: "desktop:&ubuntu"
  become: true
  gather_facts: false
  tags: ["play::zoom", "skip::zoom"]

  vars:
    zoom_version: "6.3.6.6315"

  tasks:
    - name: "Download .deb packages"
      ansible.builtin.get_url:
        url: "https://zoom.us/client/{{ zoom_version }}/zoom_amd64.deb"
        dest: "/tmp/zoom_amd64.deb"
        mode: "0644"

    - name: "Install downloaded .deb packages"
      ansible.builtin.apt:
        deb: "/tmp/zoom_amd64.deb"
        state: present
