---
nix_settings:
  experimental-features: nix-command flakes
  trusted-users: "root {{ ansible_user_id }}"

nix_nixpkgs_dir: "{{ ansible_user_dir }}/.config/nixpkgs"
nix_nixpkgs_channel: "https://nixos.org/channels/nixpkgs-unstable unstable"

nix_nixpkgs_config: |
  {
    allowUnfree = true;
  }

nix_default_packages:
  - aichat
  - ansible-language-server
  - bash-env-json
  - bat
  - bat-extras.batdiff
  - bat-extras.batgrep
  - bat-extras.batman
  - bat-extras.batpipe
  - bat-extras.batwatch
  - bottom
  - carapace
  - delta
  - devenv
  - dprint
  - eza
  - fd
  - fish-lsp
  - fluxcd
  - fx
  - go
  - go-task
  - harper
  - hexyl
  - hurl
  - isort
  - k9s
  - kdlfmt
  - kind
  - kmon
  - kubecm
  - kubectl
  - kubectx
  - lazygit
  - lazyjournal
  - lazysql
  - lsp-ai
  - lua-language-server
  - marksman
  - markdown-oxide
  - mediainfo
  - minesweep-rs
  - moar
  - mods
  - monaspace
  - navi
  - neovim
  - nixd
  - nil
  - nodePackages.vscode-json-languageserver
  - nushell
  - nufmt
  - ouch
  - presenterm
  - python312Packages.jedi-language-server
  - python312Packages.python-lsp-server
  - python312Packages.python-lsp-ruff
  - python312Packages.pylsp-mypy
  - python312Packages.pylsp-rope
  - rustup
  - rucola
  - rust-analyzer
  - ruff
  - simple-completion-language-server
  - slumber
  - starship
  - spotify-player
  - stylua
  - systemctl-tui
  - taplo
  - tealdeer
  - television
  - terraform --impure
  - typos
  - typos-lsp
  - uv
  - vagrant --impure
  - vault --impure
  - wego
  - yaml-language-server
  - yamllint
  - yazi
  - zoxide

nix_packages: []
nix_dependent_packages: []

nix_all_packages: >-
  {{ (nix_default_packages
  + nix_packages
  + nix_dependent_packages) | flatten }}

nix_fontconfig_dependent_configs:
  - path: "10-nix.conf"
    content: |-
      <dir>~/.nix-profile/share/fonts/</dir>
      <cachedir>~/.cache/fontconfig</cachedir>
