# yamllint disable rule:line-length
---
user_name: ryan
user_groups: []
user_home: "{{ ansible_user_dir | d('/home/' ~ user_name) }}"
user_shell: /usr/bin/fish

user_dotfiles_repo: "git@github.com:ryantking/system.git"
user_dotfiles_path: "{{ user_home }}/System"
user_dotfiles_version: "master"

user_dotfiles_links:
  - src: config/alacritty
  - src: config/bashrc
    dest: "{{ user_home }}/.bashrc"
    mode: "0644"
  - src: config/bat
  - src: config/doom
  - src: config/fish
  - src: config/git
  - src: config/gnupg
    dest: "{{ user_home }}/.gnupg"
    mode: "0700"
  - src: config/helix
  - src: config/k9s
  - src: config/kube
    dest: "{{ user_home }}/.kube"
    mode: "0700"
  - src: config/nushell
  - src: config/starship.toml
    mode: "0644"
  - src: config/tealdeer
  - src: config/television
  - src: config/yazi
  - src: config/wezterm
  - src: config/zellij
  - src: share/backgrounds
    dest: /usr/local/share/backgrounds
    owner: root

user_download_urls: []
