---
- name: "Import the GnuPG playbook"
  ansible.builtin.import_playbook: ../services/gpg.yml

- name: "Import the OpenSSH playbook"
  ansible.builtin.import_playbook: ../services/ssh.yml

- name: "Import the git playbook"
  ansible.builtin.import_playbook: ../services/git.yml

- name: "Import the Password Store playbook"
  ansible.builtin.import_playbook: ../services/pass.yml

- name: "Import the fonts playbook"
  ansible.builtin.import_playbook: ../services/fonts.yml

- name: "Import the dotfiles playbook"
  ansible.builtin.import_playbook: ../services/dotfiles.yml

- name: "Import the emacs playbook"
  ansible.builtin.import_playbook: ../services/emacs.yml
