---
model: openai/not-unsed

show-model-warnings: false

openai-api-key: not-used

openai-api-base: http://localhost:8989/v1/mux

dark-mode: true

pretty: true

code-theme: solarized-dark

user-input-color: #25B2BC

## Set the color for tool output (default: None)
#tool-output-color: "xxx"

## Set the color for tool error messages (default: #FF2222)
tool-error-color: "#E95678"

## Set the color for tool warning messages (default: #FFA500)
tool-warning-color: "#FAC29A"

## Set the color for assistant output (default: #0088ff)
assistant-output-color: "#B877DB"
