---
- name: Upgrade a machine with APT
  hosts: all
  gather_facts: false

  tasks:
    - name: Upgrade safe packages with refreshed cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe

    - name: Upgrade all Nix profiles
      ansible.builtin.command: >-
        bash -l -c 'nix profile upgrade --all --impure'
      register: result
      changed_when: result.stdout_lines | length > 0
