---
- name: "Add keyd PPA repository"
  ansible.builtin.apt_repository:
    repo: "{{ keyd_ppa }}"
    filename: "keyd-team"
    state: present
  when: keyd_enabled

- name: "Install keyd packages"
  ansible.builtin.apt:
    name: "{{ keyd_packages }}"
  when: keyd_enabled

- name: "Manage keyd default configuration"
  ansible.builtin.copy:
    dest: /etc/keyd/default.conf
    content: "{{ keyd_config }}"
    mode: "0644"
  when: keyd_enabled
  tags: ["keyd:config"]
