---
- name: "Install Tailscale"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -fsSL https://tailscale.com/install.sh | sh
    creates: /usr/bin/tailscale

- name: "Get Tailscale account list"
  ansible.builtin.command:
    cmd: tailscale switch --list
  changed_when: false
  register: account_list

- name: "Login to Tailscale account"
  ansible.builtin.command:
    cmd: >-
      tailscale login
      --nickname {{ account.name }}
      --auth-key {{ account.auth_key }}
      {{ account.args
      | d(tailscale_default_args)
      | join(' ') }}
  loop: "{{ tailscale_all_accounts }}"
  loop_control:
    loop_var: account
    label: "{{ account.name }}"
  register: result
  async: 120
  poll: 5
  changed_when: result.rc == 0
  failed_when:
    - result.rc != 0
    - "'profile name \"home\" already in use' not in result.stderr"
  when: account.name not in account_list.stdout

- name: "Switch to active Tailscale account"
  ansible.builtin.command: "bash -lc 'tailscale switch {{ tailscale_account }}'"
  register: result
  changed_when: "'Already on account' not in result.stdout"
  when: "tailscale_account + '*' not in account_list.stdout"

- name: "Check Tailscale status"
  ansible.builtin.command:
    cmd: tailscale status
  changed_when: false
  failed_when:
    - status.rc != 0
    - "status.stdout != 'Tailscale is stopped.'"
  register: status
  async: 120
  poll: 5

- name: "Bring Tailscale up"
  ansible.builtin.command: "bash -lc 'tailscale up'"
  async: 120
  poll: 5
  changed_when: true
  when: "status.stdout == 'Tailscale is stopped.'"
