---
- name: "Download Apt repository keys"
  ansible.builtin.get_url:
    url: "{{ repo.key_url }}"
    dest: "/usr/share/keyrings/{{ repo.name }}-archive-keyring.gpg"
    mode: "0644"
  loop: "{{ apt_all_repos }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.name }}"
  when: repo.key_url | d()

- name: "Add Apt repositories"
  ansible.builtin.apt_repository:
    repo: "{{ repo.source }}"
    filename: "{{ repo.name }}"
    state: present
  loop: "{{ apt_all_repos }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.name }}"

- name: "Install Apt packages"
  ansible.builtin.apt:
    name: "{{ apt_all_packages }}"
    update_cache: true
    state: present
  tags: ["role::apt:install"]
