---
- name: "Manage PPA repositories"
  tags: ["role::apt:ppa"]

  vars:
    ppa_name: "{{ ppa is mapping | ternary(ppa.name, ppa) }}"
    ppa_name_split: "{{ ppa_name | split('/') }}"
    ppa_owner: "{{ ppa_name_split[0] }}"
    ppa_repo: "{{ ppa_name_split[1] }}"
    apt_sources_file: >-
      /etc/apt/sources.list.d/{{ ppa_owner }}-ubuntu-{{ ppa_repo
      }}-{{ ansible_distribution_release }}.sources

  block:
    - name: "Add PPA repository"
      ansible.builtin.command:
        cmd: >-
          add-apt-repository ppa:{{ ppa_name }} -y
          {{ ppa.release is defined | ternary('-n', '') }}
        creates: "{{ apt_sources_file }}"
      loop: "{{ apt_all_ppas }}"
      loop_control:
        loop_var: ppa
        label: "{{ ppa_name }}"

    - name: "Modify PPA release when necessary"
      ansible.builtin.lineinfile:
        path: "{{ apt_sources_file }}"
        regexp: "^Suites:"
        line: "Suites: {{ ppa.release }}"
        state: present
      loop: "{{ apt_all_ppas }}"
      loop_control:
        loop_var: ppa
        label: "{{ ppa_name }}"
      when: ppa.release is defined

- name: "Install Apt packages"
  ansible.builtin.apt:
    name: "{{ apt_all_packages }}"
    update_cache: true
    state: present
  tags: ["role::apt:install"]
