---
- name: "Install the Emacs snap"
  become: true
  community.general.snap:
    name: "emacs"
    classic: true
    state: present

- name: "Clone Doom emacs"
  ansible.builtin.git:
    repo: "{{ emacs_doom_repo_url }}"
    dest: "{{ emacs_doom_install_dir }}"
    version: "{{ emacs_doom_repo_version }}"
  notify: install doom
  when: emacs_doom_enabled

- name: "Install Doom if cloned"
  ansible.builtin.meta: flush_handlers
  when: emacs_doom_enabled

- name: "Sync Doom configuration"
  ansible.builtin.shell:
    cmd: "{{ emacs_doom_install_dir }}/bin/doom sync"
    executable: "/bin/bash"
  changed_when: true
  when: emacs_doom_enabled
  tags: ["role::emacs:doom-sync"]
