---
- name: "Ensure font directories exist"
  ansible.builtin.file:
    path: "{{ dir }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ fonts_config_dir }}/conf.d"
    - "{{ ansible_env.HOME }}/.cache/fontconfig"
    - "{{ fonts_dir }}"
    - "{{ fonts_iosevka_dir | dirname }}"
  loop_control:
    loop_var: dir

- name: "Manage fontconfig"
  ansible.builtin.copy:
    dest: "{{ fonts_config_dir }}/conf.d/{{ config.path }}"
    content: |
      <?xml version='1.0'?>
      <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
      <fontconfig>
        {{ config.content | indent(2) }}
      </fontconfig>
    mode: "0644"
  loop: "{{ fonts_all_configs }}"
  loop_control:
    loop_var: config
    label: config.name
  notify: update font cache

- name: "Download NFM font"
  ansible.builtin.get_url:
    url: "{{ fonts_nfm_url }}"
    dest: "{{ fonts_nfm_dest }}"
    mode: "0644"
  notify: update font cache
  tags: ["fonts:nfm"]

- name: "Clone Iosevka"
  ansible.builtin.git:
    repo: "{{ fonts_iosevka_repo }}"
    dest: "{{ fonts_iosevka_dir }}"
    version: "{{ fonts_iosevka_version }}"
    depth: 1
    force: true
  tags: ["fonts:iosevka"]

- name: "Install Iosevka dependencies"
  community.general.npm:
    path: "{{ fonts_iosevka_dir }}"
    state: present
  tags: ["fonts:iosevka"]

- name: "Create Iosevka build plans"
  ansible.builtin.template:
    src: "templates/iosevka-build-plan.toml.j2"
    dest: "{{ fonts_iosevka_dir }}/private-build-plans.toml"
    trim_blocks: true
    lstrip_blocks: true
    mode: "0644"
  tags: ["fonts:iosevka"]

- name: "Build Iosevka fonts"
  ansible.builtin.command:
    cmd: npm run build -- ttf::{{ build_plan.name }}
    chdir: "{{ fonts_iosevka_dir }}"
  loop: "{{ fonts_iosevka_build_plans }}"
  loop_control:
    loop_var: build_plan
    label: "{{ build_plan.name }}"
  changed_when: true
  tags: ["fonts:iosevka:build", "fonts:iosevka"]

- name: "Install Iosevka fonts"
  ansible.builtin.copy:
    src: "{{ fonts_iosevka_dir }}/dist/{{ build_plan.name }}/TTF/"
    dest: "{{ fonts_dir }}/{{ build_plan.name }}"
    remote_src: true
    mode: "0755"
  loop: "{{ fonts_iosevka_build_plans }}"
  loop_control:
    loop_var: build_plan
  notify: update font cache
  tags: ["fonts:iosevka"]
