---
dotfiles_repo: "git@github.com:ryantking/system.git"
dotfiles_path: "{{ ansible_user_dir | d(ansible_env.HOME) }}/System"
dotfiles_version: "master"

dotfiles_links:
  - from: doom
    recurse: true
  - from: git
  - from: k9s
  - from: bashrc
    to: .bashrc
  - from: tealdeer.toml
    to: .config/tealdeer/config.toml
  - from: gnupg
    to: .gnupg
    recurse: true
    mode: "0700"
